### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by legalnonsense** [harishkrupo/oauth2ms#25]
Recently upgraded system (manjaro). Previous set up worked flawlessly. Now, running `oauth2ms` gives the following error:

```
Traceback (most recent call last):
  File "/usr/bin/oauth2ms", line 247, in <module>
    token = fetch_token_from_cache(app_state)
  File "/usr/bin/oauth2ms", line 181, in fetch_token_from_cache
    return result["access_token"]
TypeError: 'NoneType' object is not subscriptable
```

I am not sure what might have caused this and happy to provide any additional info. This package has been great and it appears that something else has now broken it. Thanks for the work and making this available to us

**Comment by legalnonsense** [comment]
Just tried to install with the installation instructions on the readme instead of from AUR. Received the following error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyopenssl 22.1.0 requires cryptography<39,>=38.0.0, but you have cryptography 3.4.8 which is incompatible.
pdfminer-six 20220524 requires cryptography>=36.0.0, but you have cryptography 3.4.8 which is incompatible.
```

**Comment by legalnonsense** [comment]
Turns out it was not an update; I just had to delete the cache (which I found at `~/.local/share/oauth2ms`) and everything is working again.

**Comment by legalnonsense** [comment]
Turns out it was not an update; I just had to delete the cache (which I found at ~/.local/share/oauth2ms) and everything is working again.

**Comment by robstewart57** [comment]
I came across this issue too. My Azure app's client secret key had expired. Perhaps oauth2ms could provide guidance, rather than `TypeError: 'NoneType' object is not subscriptable`. Either a hint to check if a client secret key may have expired, or a hint to remove `~/.local/share/oauth2ms/credentials.bin`.
