### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jimmerricks** [harishkrupo/oauth2ms#6]
I am attempting to setup `oauth2ms` to work with `mbsync`, and while troubleshooting ran into the following error:

```
Traceback (most recent call last):
  File "~/.local/bin/oauth2ms", line 247, in <module>
    token = fetch_token_from_cache(app_state)
  File "~/.local/bin/oauth2ms", line 181, in fetch_token_from_cache
    return result["access_token"]
TypeError: 'NoneType' object is not subscriptable
```

This occurs when executing both `mbsync -a` and `oauth2ms --encode-xoauth2`. I am not sure what is producing this as it seemed to be working fine, albeit with the incorrect base64.

**Comment by harishkrupo** [comment]
If the code has entered `fetch_token_from_cache`, then it has found the credentials file and loaded it. It seems like the credentials file might be corrupted.  Could you dump the accounts variable [here](https://github.com/harishkrupo/oauth2ms/blob/main/oauth2ms#L178)? Also the result variable [here](https://github.com/harishkrupo/oauth2ms/blob/main/oauth2ms#L180)? It will help with debugging. 
Please use `pp.pprint(...)` to dump the variables.

**Comment by jimmerricks** [comment]
Thanks for the response. I added `pp.print(accounts)` and `pp.print(result)` and this was the output (with some changes to the ids):

```
[   {   'authority_type': 'MSSTS',
        'environment': 'login.microsoftonline.com',
        'home_account_id': '1a0b0b01-e0a3-4f97-9d7f-4a2908607c6a.d54d65af-91e2-44b4-b9cb-0gg38e55eb41',
        'local_account_id': 'e9181b38-8eb4-4398-8ed2-761dd1830400',
        'realm': 'ca6554cd-1d6c-4328-98ee-84214b1a7d9c',
        'username': '<email-address>'}]
None
Traceback (most recent call last):
  File "~/.local/bin/oauth2ms", line 249, in <module>
    token = fetch_token_from_cache(app_state)
  File "~/.local/bin/oauth2ms", line 183, in fetch_token_from_cache
    return result["access_token"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by harishkrupo** [comment]
The accounts output looks okay. It is possible that the token cache is corrupted. Could you try deleting the file in `$XDG_DATA_HOME/share/oauth2ms/credentials.bin` and trying again?

**Comment by jimmerricks** [comment]
That seems to have done the trick for the TypeError, but it is still not properly authenticating. Running `mbsync -Dna` gets me:

```
Reading configuration file ~/.mbsyncrc
Channel <channel-name>
Opening master store <master-store-name>...
Resolving outlook.office365.com... ok
Connecting to outlook.office365.com (40.100.146.18:143)... 
Opening slave store <slave-store-name>...
* OK The Microsoft Exchange IMAP4 service is ready. [UfB.....AG4]
>>> 1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 LOGINDISABLED STARTTLS SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
>>> 2 STARTTLS
2 OK Begin TLS negotiation now.
Connection is now encrypted
>>> 3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
Logging in...
Authenticating with SASL mechanism XOAUTH2...
>>> 4 AUTHENTICATE XOAUTH2 dRN.....ALQ
4 NO AUTHENTICATE failed.
IMAP command 'AUTHENTICATE XOAUTH2 dRN.....ALQ' returned an error: NO AUTHENTICATE failed.
```

I guess this is not a problem with `oauth2ms`. Perhaps I didn't correctly install `cyrus-sasl-xoauth2`. What do you think?

**Comment by harishkrupo** [comment]
Few things to remember/try:
1. Don't use `--encode-xoauth2` in the mbsyncrc
2. In `AUTHENTICATE XOAUTH2 dRN.....ALQ` check that the `dRN.....ALQ` part matches the output from `oauth2ms --encode-xoauth2`
3. run `echo dRN.....ALQ | base64 -d` and copy the output after auth=Bearer and paste it in https://jwt.ms. Check if there are any mistakes in email, client and other details.

**Comment by jimmerricks** [comment]
Everything seems ok. If the issue is not with `cyrus-sasl-xoauth2` it might be related to how I set up the Azure application. I was unable to access Azure active directory with my work email, so used a personal email address. This lead to me setting up a tenant and adding my work email as a user, and then creating the application from there.

Do you have any suggestions for how to resolve this? I am determined to get this working, but am aware this has strayed beyond your code.

**Comment by harishkrupo** [comment]
AFAIK, fetching and sending emails is tied to the client, tenant, and application. All these three must be part of the same org for it to work. I am not sure if creating a separate tenant will permit you to access mailboxes that are part of the other tenant.
I think the best option is to ask your organization to enable azure portal access.
That said, if you find a solution using this method, please do open a PR to update the docs :)

**Comment by jimmerricks** [comment]
Thanks for your help. I will see if I can get them to enable Azure for the account.

**Comment by gitbxf4** [comment]
In case others find their way here. I just had this "'NoneType' object is not subscriptable" error pop-up on two of my computers using mbsync for IMAP with my organization's Outlook email. Removing credentials.bin and re-running mbsync took me to a webpage to reauthorize. Now I'm getting email again. Thank you for oauth2ms.
